apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedConfigMap
metadata:
  name: coredns
  namespace: kube-system
spec:
  template:
    metadata:
      name: coredns
      namespace: kube-system
    data:
      Corefile: |
        .:53 {
            errors
            health
            kubernetes cluster.local in-addr.arpa ip6.arpa {
               pods insecure
               upstream
               fallthrough in-addr.arpa ip6.arpa
            }
            prometheus :9153
            proxy . /etc/resolv.conf
            cache 30
            reload
            federation cluster.local {
               production prod.f8n.org
               staging stage.f8n.org
               upstream
            }
        }
---
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedConfigMapPlacement
metadata:
  name: coredns
  namespace: kube-system
spec:
  clusterNames:
  - "cluster1"
  - "cluster2"
